### ISSUE TITLE
Hello! Where do we write issues?

### ISSUE THREAD

**Issue by gaurav21r** [expandjs/expandjs.github.io#1]
First of all Congratulations on an amazing UI Library! Really this is so much better and easier than Polymer!

My team and I plan to contribute extensively and need to interact with you through Issues. So I guess my first suggestion would be to create one "General Repo" where we can raise issues / have discussions etc. which are more general to ExpandJS rather than relating to any element.

Is that here?

**Comment by Pupix** [comment]
Thank you for your interest in our library!

At the moment we do not have a "General Repo" where people can raise generic issues, but we can start using this for such things.

As a rule of thumb try to stick with these:

- For element specific issues, use the appropriate repository.
- For any other type of issues/discussions use this repository.

Cheers!

**Comment by gaurav21r** [comment]
@Pupix Thanks for your response. You should probably document this on your site? 

Also, just a marketing tip. People usually judge the success of the next framework they use by downloads / commit activity etc. One such "metric" is the number of GitHUB Stars. May seem unimportant but many people use that as a good enough data point to evaluate.

Probably market the framework so that stars on the main site redirect here?

**Comment by Pupix** [comment]
> @Pupix Thanks for your response. You should probably document this on your site?

We have just updated the website's FAQ.

>Also, just a marketing tip. People usually judge the success of the next framework they use by downloads / commit activity etc. One such "metric" is the number of GitHUB Stars. May seem unimportant but many people use that as a good enough data point to evaluate.

>Probably market the framework so that stars on the main site redirect here?

What you are talking about is called "social proof". We've tested the GitHub starring system in the past, but the only thing it did was redirecting the user here instead of actually adding a new star, thus is was moving the visitor away from our website.

Checking other libraries/frameworks (polymer, react ecc.) we also noticed that most seem to stay away from this, because these are not one time purchases like most products, where you can go "Gotcha! You bought my product!, I got the money, you are on your own now!".

In our case the user has to be engaged with the the "product" for much longer and a pretty number is not gonna make him change his App to fit your product's vision. It is your product that should help the user achieve what he wants to do, otherwise they will just look somewhere else.

This is what we are trying to do, to solve specific problems that arise from web development in the highest possible quality, and let that speak for itself.

---

Having said this, 60 starts is not that much anyway. When the v1.0 will arrive we can take a look at this again, hopefully the number of stars will be higher by then, and find better marketing solutions.

**Comment by gaurav21r** [comment]
Your vision is both honourable and exciting! Can't wait to see the future of expandjs! :)

**Comment by mibamur** [comment]
+1
